apiVersion: v1
kind: Service
metadata:
  name: simple-python-app
  labels:
    app: simple-python-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: simple-python-app